name: Deploy on Pinata
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Pinata
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: 'TD2_'
          path: './src'
          pinata-api-key: ${{ secrets.e21acbf33e9b326f1fe2 }}
          pinata-secret-api-key: ${{ secrets.e85aea51c1e97cf7315ef76d20eb2074dc4d38c62711beece359dd626227bc78 }}
          verbose: true
          remove-old: true
